### ISSUE TITLE
Establish website using Django and Elastic Beanstalk

### ISSUE THREAD

**Issue by yvr2** [robmarano/2018_Summer_Adv_Python_Project#12]
http://tweedata.us-west-2.elasticbeanstalk.com/admin/login/?next=/admin/

**Comment by celestinosalim** [comment]
website being updated in localhost, will be deployed  when done.

**Comment by celestinosalim** [comment]
website being updated in localhost, will be deployed  when done.

**Comment by celestinosalim** [comment]
http://tweedatav2.us-west-2.elasticbeanstalk.com/accounts/login/.     Website deployed for more test(included user auth, added SendGrid ),  is not a final product,  need configurations.

**Comment by celestinosalim** [comment]
website without security SSL/HTTPs.  won't allow you to login with facebook.
will be deployed behind HTTPS.  after config..

**Comment by celestinosalim** [comment]
https://tweedata.com/accounts/login
