### ISSUE TITLE
Create histogram representation of sample data

### ISSUE THREAD

**Issue by yvr2** [robmarano/2018_Summer_Adv_Python_Project#6]

**Comment by vladmakutoff** [comment]
Here is the code (I will create graph labels tomorrow - three charts for each keyword count by state):

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import csv
import pandas as pd
import numpy as np
import datetime

df=pd.read_csv('C:/Users/vm555/Downloads/data.csv', header=0, sep=',', index_col=0, encoding='utf8') 

df1=df[df['state'].notnull()]
df1['time']=pd.to_datetime(df1['time'], format='%a %b %d %H:%M:%S +%f %Y')
df1['time']=df1['time'].dt.round('60min')
df2=df1.groupby(['time', 'state', 'keyword']).size().reset_index()
df2.columns = ['Time', 'State', 'Key Word', 'Word Count']

# Word Count for Lit
df3=df2[df2['Key Word']=='lit']
df3=df3.groupby(['State'])['Word Count'].sum().reset_index()
df3.hist()
df3.set_index('State')['Word Count'].plot.bar()

# Word Count for Ratchet
df4=df2[df2['Key Word']=='ratchet']
df4=df4.groupby(['State'])['Word Count'].sum().reset_index()
df4.hist()
df4.set_index('State')['Word Count'].plot.bar()

# Word Count for Adulting
df5=df2[df2['Key Word']=='adulting']
df5=df5.groupby(['State'])['Word Count'].sum().reset_index()
df5.hist()
df5.set_index('State')['Word Count'].plot.bar()``
